/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.100
 * Generated at: 2025-09-24 16:26:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"vi\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Hệ thống quản lý sản phẩm đa ngôn ngữ</title>\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("    <style>\r\n");
      out.write("        .hero-section {\r\n");
      out.write("            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("        .feature-card {\r\n");
      out.write("            background: white;\r\n");
      out.write("            border-radius: 15px;\r\n");
      out.write("            padding: 30px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            box-shadow: 0 10px 30px rgba(0,0,0,0.1);\r\n");
      out.write("            transition: transform 0.3s ease;\r\n");
      out.write("            margin-bottom: 30px;\r\n");
      out.write("        }\r\n");
      out.write("        .feature-card:hover {\r\n");
      out.write("            transform: translateY(-10px);\r\n");
      out.write("        }\r\n");
      out.write("        .feature-icon {\r\n");
      out.write("            font-size: 3rem;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        .btn-hero {\r\n");
      out.write("            padding: 15px 40px;\r\n");
      out.write("            font-size: 1.2rem;\r\n");
      out.write("            border-radius: 50px;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("        .btn-hero:hover {\r\n");
      out.write("            transform: translateY(-2px);\r\n");
      out.write("            box-shadow: 0 10px 25px rgba(0,0,0,0.2);\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- Hero Section -->\r\n");
      out.write("    <div class=\"hero-section\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row align-items-center\">\r\n");
      out.write("                <div class=\"col-lg-6\">\r\n");
      out.write("                    <h1 class=\"display-3 fw-bold mb-4\">\r\n");
      out.write("                        <i class=\"fas fa-globe me-3\"></i>\r\n");
      out.write("                        Hệ thống quản lý sản phẩm đa ngôn ngữ\r\n");
      out.write("                    </h1>\r\n");
      out.write("                    <p class=\"lead mb-5\">\r\n");
      out.write("                        Quản lý sản phẩm của bạn với khả năng hỗ trợ nhiều ngôn ngữ. \r\n");
      out.write("                        Dễ dàng thêm, sửa, xóa và xem chi tiết sản phẩm bằng các ngôn ngữ khác nhau.\r\n");
      out.write("                    </p>\r\n");
      out.write("                    <div class=\"d-grid gap-3 d-md-flex\">\r\n");
      out.write("                        <a href=\"products\" class=\"btn btn-warning btn-hero\">\r\n");
      out.write("                            <i class=\"fas fa-rocket me-2\"></i>Bắt đầu ngay\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <a href=\"#features\" class=\"btn btn-outline-light btn-hero\">\r\n");
      out.write("                            <i class=\"fas fa-info-circle me-2\"></i>Tìm hiểu thêm\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-6 text-center\">\r\n");
      out.write("                    <i class=\"fas fa-boxes\" style=\"font-size: 15rem; opacity: 0.3;\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Features Section -->\r\n");
      out.write("    <div class=\"container py-5\" id=\"features\">\r\n");
      out.write("        <div class=\"row mb-5\">\r\n");
      out.write("            <div class=\"col-12 text-center\">\r\n");
      out.write("                <h2 class=\"display-4 fw-bold mb-3\">Tính năng nổi bật</h2>\r\n");
      out.write("                <p class=\"lead text-muted\">Khám phá những tính năng mạnh mẽ của hệ thống</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("                <div class=\"feature-card\">\r\n");
      out.write("                    <i class=\"fas fa-language feature-icon text-primary\"></i>\r\n");
      out.write("                    <h3 class=\"fw-bold mb-3\">Đa ngôn ngữ</h3>\r\n");
      out.write("                    <p class=\"text-muted\">\r\n");
      out.write("                        Hỗ trợ nhiều ngôn ngữ bao gồm Tiếng Việt, English, Français, Deutsch và 日本語. \r\n");
      out.write("                        Dễ dàng chuyển đổi giữa các ngôn ngữ.\r\n");
      out.write("                    </p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("                <div class=\"feature-card\">\r\n");
      out.write("                    <i class=\"fas fa-cogs feature-icon text-success\"></i>\r\n");
      out.write("                    <h3 class=\"fw-bold mb-3\">Quản lý dễ dàng</h3>\r\n");
      out.write("                    <p class=\"text-muted\">\r\n");
      out.write("                        Giao diện trực quan, dễ sử dụng. Thêm, sửa, xóa sản phẩm chỉ với vài cú click. \r\n");
      out.write("                        Quản lý danh mục và thông tin giao hàng.\r\n");
      out.write("                    </p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("                <div class=\"feature-card\">\r\n");
      out.write("                    <i class=\"fas fa-database feature-icon text-info\"></i>\r\n");
      out.write("                    <h3 class=\"fw-bold mb-3\">Cơ sở dữ liệu mạnh mẽ</h3>\r\n");
      out.write("                    <p class=\"text-muted\">\r\n");
      out.write("                        Sử dụng MySQL với thiết kế chuẩn hóa. Đảm bảo tính nhất quán và hiệu suất cao \r\n");
      out.write("                        cho việc lưu trữ dữ liệu đa ngôn ngữ.\r\n");
      out.write("                    </p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("                <div class=\"feature-card\">\r\n");
      out.write("                    <i class=\"fas fa-mobile-alt feature-icon text-warning\"></i>\r\n");
      out.write("                    <h3 class=\"fw-bold mb-3\">Responsive Design</h3>\r\n");
      out.write("                    <p class=\"text-muted\">\r\n");
      out.write("                        Giao diện thích ứng với mọi thiết bị. Sử dụng Bootstrap 5 đảm bảo trải nghiệm \r\n");
      out.write("                        tốt trên desktop, tablet và mobile.\r\n");
      out.write("                    </p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("                <div class=\"feature-card\">\r\n");
      out.write("                    <i class=\"fas fa-search feature-icon text-danger\"></i>\r\n");
      out.write("                    <h3 class=\"fw-bold mb-3\">Tìm kiếm nhanh</h3>\r\n");
      out.write("                    <p class=\"text-muted\">\r\n");
      out.write("                        Tìm kiếm sản phẩm theo tên, danh mục hoặc mô tả. Lọc sản phẩm theo khả năng \r\n");
      out.write("                        giao hàng và các tiêu chí khác.\r\n");
      out.write("                    </p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("                <div class=\"feature-card\">\r\n");
      out.write("                    <i class=\"fas fa-shield-alt feature-icon text-secondary\"></i>\r\n");
      out.write("                    <h3 class=\"fw-bold mb-3\">Bảo mật cao</h3>\r\n");
      out.write("                    <p class=\"text-muted\">\r\n");
      out.write("                        Sử dụng PreparedStatement để tránh SQL Injection. Xác thực dữ liệu đầu vào \r\n");
      out.write("                        và mã hóa kết nối cơ sở dữ liệu.\r\n");
      out.write("                    </p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Statistics Section -->\r\n");
      out.write("    <div class=\"bg-light py-5\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row text-center\">\r\n");
      out.write("                <div class=\"col-lg-3 col-md-6 mb-4\">\r\n");
      out.write("                    <i class=\"fas fa-language fa-3x text-primary mb-3\"></i>\r\n");
      out.write("                    <h3 class=\"fw-bold\">5</h3>\r\n");
      out.write("                    <p class=\"text-muted\">Ngôn ngữ hỗ trợ</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-3 col-md-6 mb-4\">\r\n");
      out.write("                    <i class=\"fas fa-boxes fa-3x text-success mb-3\"></i>\r\n");
      out.write("                    <h3 class=\"fw-bold\">∞</h3>\r\n");
      out.write("                    <p class=\"text-muted\">Sản phẩm có thể quản lý</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-3 col-md-6 mb-4\">\r\n");
      out.write("                    <i class=\"fas fa-tags fa-3x text-info mb-3\"></i>\r\n");
      out.write("                    <h3 class=\"fw-bold\">∞</h3>\r\n");
      out.write("                    <p class=\"text-muted\">Danh mục sản phẩm</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-3 col-md-6 mb-4\">\r\n");
      out.write("                    <i class=\"fas fa-users fa-3x text-warning mb-3\"></i>\r\n");
      out.write("                    <h3 class=\"fw-bold\">24/7</h3>\r\n");
      out.write("                    <p class=\"text-muted\">Hỗ trợ trực tuyến</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- CTA Section -->\r\n");
      out.write("    <div class=\"py-5\" style=\"background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\">\r\n");
      out.write("        <div class=\"container text-center text-white\">\r\n");
      out.write("            <h2 class=\"display-4 fw-bold mb-4\">Sẵn sàng bắt đầu?</h2>\r\n");
      out.write("            <p class=\"lead mb-5\">Trải nghiệm hệ thống quản lý sản phẩm đa ngôn ngữ ngay hôm nay</p>\r\n");
      out.write("            <a href=\"products\" class=\"btn btn-warning btn-hero btn-lg\">\r\n");
      out.write("                <i class=\"fas fa-arrow-right me-2\"></i>Vào hệ thống\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Footer -->\r\n");
      out.write("    <footer class=\"bg-dark text-white py-4\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-6\">\r\n");
      out.write("                    <h5><i class=\"fas fa-globe me-2\"></i>Multi-Language Product System</h5>\r\n");
      out.write("                    <p class=\"text-muted\">Hệ thống demo quản lý sản phẩm đa ngôn ngữ sử dụng JSP Servlet</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6 text-end\">\r\n");
      out.write("                    <p class=\"text-muted mb-0\">\r\n");
      out.write("                        <i class=\"fas fa-code me-2\"></i>Built with JSP, Servlet, MySQL & Bootstrap 5\r\n");
      out.write("                    </p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap JS -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <script src=\"js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
